### ISSUE TITLE
Hello! Question about watching the trained model perform on a track.

### ISSUE THREAD

**Issue by aatishdubey** [jastfkjg/DDPG_Torcs_PyTorch#4]
I've done similar work but with tensorflow. I've finished training my model but now how do I actually test it on a track?

**Comment by jastfkjg** [comment]
If you have already a policy model, you can just pass the states from gym_torcs to your policy and get the action.  it is actually the same as training.

**Comment by aatishdubey** [comment]
Ahh yes, I managed to figure it out eventually while going through your code. Thanks a lot!
